name: mudad_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  get: ^4.6.6
  share: ^2.0.4
#  flutter_local_notifications: ^16.3.2
  flutter_switch: ^0.3.2
  get_storage: ^2.1.1
  google_maps_flutter: ^2.2.0
  geocoding: ^2.0.1
  flutter_google_places: ^0.3.0
  flutter_polyline_points: ^1.0.0
#  awesome_snackbar_content: ^0.0.8
  google_maps_webservice: ^0.0.19
  shared_preferences: ^2.2.2
  search_map_place_updated: ^0.0.4
  flutter_cache_manager: ^3.3.1
  modal_progress_hud_nsn: ^0.5.1
  flutter_spinkit: ^5.2.0
  equatable: ^2.0.4
#  flutter_otp_text_field: ^1.1.1
  pin_code_fields: ^8.0.1
  circular_countdown_timer: ^0.2.3
#  http: ^0.13.4
  flutter_paytabs_bridge: ^2.6.8
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  coupon_uikit: ^0.2.1
  intl_phone_number_input: ^0.7.4
  uuid: ^4.3.0
  #  android_alarm_manager_plus: ^3.0.4
  #  workmanager: ^0.5.2

  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  dio: ^5.4.1

  timezone: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
    - assets/drawer_assets/
    - assets/payment_assets/
    - assets/images/
    - assets/locals/
