// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_IxhXqXyv1lirtOUYBmXhHBdABQTyG1w',
    appId: '1:483072843151:web:6623a07d042ad45f363ffa',
    messagingSenderId: '483072843151',
    projectId: 'test-dd4b2',
    authDomain: 'test-dd4b2.firebaseapp.com',
    storageBucket: 'test-dd4b2.appspot.com',
    measurementId: 'G-TLF7WW6J3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBij_K2QBUanCUdUpNoXlbn8nNiDpxHNO0',
    appId: '1:483072843151:android:0ae915da40bd3a46363ffa',
    messagingSenderId: '483072843151',
    projectId: 'test-dd4b2',
    storageBucket: 'test-dd4b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrTD8EGKBqx2r_sW0AUr69PNrUXLZR_SU',
    appId: '1:483072843151:ios:0de6d7d447cdb6cc363ffa',
    messagingSenderId: '483072843151',
    projectId: 'test-dd4b2',
    storageBucket: 'test-dd4b2.appspot.com',
    iosBundleId: 'com.example.mudadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrTD8EGKBqx2r_sW0AUr69PNrUXLZR_SU',
    appId: '1:483072843151:ios:0ec3e40fa868acf4363ffa',
    messagingSenderId: '483072843151',
    projectId: 'test-dd4b2',
    storageBucket: 'test-dd4b2.appspot.com',
    iosBundleId: 'com.example.mudadApp.RunnerTests',
  );
}
