// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQD-TvmzvCsx7Lcf6sxDNivAYKD_Iz-0',
    appId: '1:556936817748:web:7638a508409372551091c1',
    messagingSenderId: '556936817748',
    projectId: 'mudad-app-414614',
    authDomain: 'mudad-app-414614.firebaseapp.com',
    storageBucket: 'mudad-app-414614.appspot.com',
    measurementId: 'G-Q7B57NJ6S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO_F1l9eFo8qJKC5AgixgLuTJOyxo8ehA',
    appId: '1:556936817748:android:b055be0d172966cd1091c1',
    messagingSenderId: '556936817748',
    projectId: 'mudad-app-414614',
    storageBucket: 'mudad-app-414614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUC9PuSoMI-Jmi3Izr098Yce-uAsS-GqA',
    appId: '1:556936817748:ios:08ab8fc4b4236adc1091c1',
    messagingSenderId: '556936817748',
    projectId: 'mudad-app-414614',
    storageBucket: 'mudad-app-414614.appspot.com',
    iosBundleId: 'com.example.mudadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUC9PuSoMI-Jmi3Izr098Yce-uAsS-GqA',
    appId: '1:556936817748:ios:f976c3ec763814ce1091c1',
    messagingSenderId: '556936817748',
    projectId: 'mudad-app-414614',
    storageBucket: 'mudad-app-414614.appspot.com',
    iosBundleId: 'com.example.mudadApp.RunnerTests',
  );
}
